### PR TITLE
Add VersionSQL

### PR DESCRIPTION
**Pull request by MikeTV**
VersionSQL is a version control add-in for SQL Server Management Studio, free for SQL Server Express Edition databases

### CODE REVIEW

**Comment by hilmanski** [comment]
in the pricing, it shows only trial for 15 days, which is not align, with freestuffdev
will close this for now

**Comment by MikeTV** [comment]
@hilmanski The free version is free with the "SQL Server Express Edition only" limitation.  The download also contains a trial of the paid edition.  I can see how the wording is confusing.

**Comment by hilmanski** [comment]
can you provide me with the link.
and is that mean a free forever or for how long

**Comment by MikeTV** [comment]
Yes, free forever:

https://www.versionsql.com/help/faq/licensing/#will-versionsql-free-expire
https://www.versionsql.com/help/faq/licensing/#what-are-the-limitations-of-versionsql-free
https://www.versionsql.com/help/faq/licensing/#whats-the-difference-between-free-and-professional

The "SQL Server Express Edition only" requirement aligns with Microsoft's licensing decision - SQL Server Express Edition itself is free, so why should you have to pay for version control? This makes VersionSQL ideal for hobby, educational, and even business use in some situations.  It's the only free option in its class.

Thank you very much for providing such a useful index of free tools and resources!

**Pull request closed without merging**
