### PR TITLE
Fixed the irregularly sized icons

### PR DESCRIPTION
**Pull request by harshitsahush**

### CODE REVIEW

**Comment by harshitsahush** [comment]
Since github isn't really showing the difference in the .css file, here's what i've done.
Screenshot from 2023-01-13 13-23-15

**Comment by hilmanski** [comment]
if we remove the max-height, then I believe some icons will be stretched down (on height)

**Comment by harshitsahush** [comment]
Since the width and height have been fixed, the image should occupy the given size, and the object-fit should ensure that it doesn't flow out or anything.

I did check the icons after applying these changes. Could you please provide a screenshot where the icons have stretched?

**Comment by harshitsahush** [comment]
Did you check out the changes?

**Comment by hilmanski** [comment]
hi @harshitsahush 
Yap here is the sample, when just removing both max and min width

Screen Shot 2023-01-22 at 06 05 55

So I can't merge it for now.

**Comment by harshitsahush** [comment]
Ah, I see. Well, I'll try and fix it ASAP.

**Pull request closed without merging**
