### PR TITLE
Create clever-cloud.md

### PR DESCRIPTION
**Pull request by Afranioalves**
# Clever Cloud
Add clever cloud as a free database hosting tool

@aosccode

### CODE REVIEW

**Comment by antonio-pedro99** [comment]
@Afranioalves contribuição inválida.

**Comment by hilmanski** [comment]
please clarify, what's the free offer

**Comment by Afranioalves** [comment]
> please clarify, what's the free offer

777- The free offering is database hosting such as Mysql, Postgresql, MongoBD and others.

**Comment by hilmanski** [comment]
Hi, we need more detail info. take a look at other item as reference

**Pull request closed without merging**
