### PR TITLE
add RunJS

### PR DESCRIPTION
**Pull request by lukehaas**

### CODE REVIEW

**Comment by hilmanski** [comment]
hi @lukehaas 
can you clarify what is free? add it in content

**Comment by lukehaas** [comment]
@hilmanski, thanks. That's been updated now.

**Comment by hilmanski** [comment]
HI @lukehaas 
unfortunately "All core features"  is not clear enough for the visitor.
Please list the features on that section
thanks

**Comment by hilmanski** [comment]
Thanks @lukehaas

**Pull request merged**
