### PR TITLE
Added  windframe

### PR DESCRIPTION
**Pull request by Speedwares**

### CODE REVIEW

**Comment by hilmanski** [comment]
Can you clarify is this  free offers, valid 1 time or per month?
and please update the content to this, instead of "free offer" if so:

20 free code exports
Free blocks
Save 2 websites or prototypes
10 AI Requests

**Comment by Speedwares** [comment]
Hey @hilmanski The offers are valid 1 time. 

I just updated the description to make it clearer

**Comment by Speedwares** [comment]
Hey @hilmanski 

Just bumping this up

**Comment by hilmanski** [comment]
I apologize beforehand, but I don't think it's suitable for freestuffdev, if the offer just for 1 time.

**Pull request closed without merging**
