### PR TITLE
Create hackerrank.md

### PR DESCRIPTION
**Pull request by wal33dahmad**

### CODE REVIEW

**Comment by hilmanski** [comment]
are you sure it's free? https://www.hackerrank.com/products/pricing/

**Comment by wal33dahmad** [comment]
image

**Comment by hilmanski** [comment]
Thanks for your contribution. Do you mind to share any link on that page, that shows this info (that its free for the developer)

**Comment by wal33dahmad** [comment]
Sure. I will write in the description and let me see if I can find a link for that. And Thank you for accepting my PR.

**Comment by wal33dahmad** [comment]
Hi @hilmanski I'm facing difficulty in cloning this repo. Also got an error when I "git init" and "git add ." on the downloaded files. Please let me know how can I edit my file. 
I want to add the following line to my file. 
"Sign up for free and get better at your Problem-Solving skills in Algos, Data Structures, AI, C, Java, Python and more."

**Comment by wal33dahmad** [comment]
@hilmanski thanks for guiding me. I've updated the file. 😃

**Pull request merged**
