### PR TITLE
Create static-app.md

### PR DESCRIPTION
**Pull request by andrianvaleanu**

### CODE REVIEW

**Comment by hilmanski** [comment]
Hi @andrianvaleanu can you please confirm that the free plan only valid for 7 days?

**Comment by andrianvaleanu** [comment]
> Hi @andrianvaleanu can you please confirm that the free plan only valid for 7 days?

Hi, yes, I confirm.

**Comment by andrianvaleanu** [comment]
@hilmanski Hi, It's live?

**Comment by hilmanski** [comment]
Unfortunately, we don't accept if the free trial is only 7 days. I'll mark it as a paid product

**Pull request merged**
