### PR TITLE
Add Dotenv

### PR DESCRIPTION
**Pull request by motdotla**
Hi @hilmanski 👋,

Came across your site. Pretty cool! Thought I'd add to your list with Dotenv. https://dotenv.org

Thanks!

### CODE REVIEW

**Comment by hilmanski** [comment]
thanks!

**Comment by hilmanski** [comment]
You might also submit it at https://finddev.tools/

**Comment by hilmanski** [comment]
Is the behavior correct? it redirect to doppler site

**Comment by motdotla** [comment]
@hilmanski thank you for catching that. Doppler recently purchased the .com domain from the prior owner so it redirects to them.  🤷‍♂️

I'm fixing to the .org now.

**Comment by motdotla** [comment]
Fixed here: https://github.com/hilmanski/freeStuffDev/pull/236

**Pull request merged**
